name: statsbomb_env
channels:
  - snowflake
  - conda-forge
dependencies:
  - python=3.10
  - streamlit=1.38
  - plotly=5.24
  - pandas=2.2
  - numpy=2.1
  - scikit-learn=1.5
  - networkx=3.4
  - pyarrow=16
  - requests
  - python-dotenv
